start local DBus on test_init
The local DBus has to be started at test_init and not before, since
a test_cleanup kills the test. test_cleanup is an essential part
of test_init to guarantee a clean test environment.

diff --git a/test/bin/test-functions b/test/bin/test-functions
--- a/test/bin/test-functions
+++ b/test/bin/test-functions
@@ -43,17 +43,8 @@ export DB_BOB_2_ALICE="${TEST_BASE}/bob_to_alice.db"
 export SHARED_SECRET=$(cat ${TEST_BASE}/test/test-data/shared-secret)
 export SHARED_SECRET_FILE="${TEST_BASE}/test/test-data/shared-secret-very-long"
 
-# setup local DBUS for testing
-mkdir -p /tmp/qkd-test-dbus &> /dev/null
-rm -f /tmp/qkd-test-dbus/qkd-dbus.pid &> /dev/null
-dbus-daemon --config-file ${TEST_BASE}/test/test-data/qkd-test-dbus.conf
 export QKD_DBUS_SESSION_ADDRESS="unix:path=/tmp/qkd-test-dbus/qkd_dbus_socket"
 alias qkd_qdbus='qdbus --address ${QKD_DBUS_SESSION_ADDRESS}'
-DBUS_ID=$(qkd_qdbus org.freedesktop.DBus / GetId)
-if [ -z ${DBUS_ID} ]; then
-    echo 'Failed to launch local DBus for testing.'
-    exit 1
-fi
 
 
 # --------------------------------------------------
@@ -123,6 +114,16 @@ function test_init() {
 
     # clean up any remants of previous tests
     test_cleanup
+
+    # setup local DBUS for testing
+    mkdir -p /tmp/qkd-test-dbus &> /dev/null
+    rm -f /tmp/qkd-test-dbus/qkd-dbus.pid &> /dev/null
+    dbus-daemon --config-file ${TEST_BASE}/test/test-data/qkd-test-dbus.conf
+    DBUS_ID=$(qkd_qdbus org.freedesktop.DBus / GetId)
+    if [ -z ${DBUS_ID} ]; then
+        echo 'Failed to launch local DBus for testing.'
+        exit 1
+    fi
 }
 
 
