test-mod-error-estimation: deterministic precondition checks

diff --git a/test/bin/modules/test-mod-error-estimation b/test/bin/modules/test-mod-error-estimation
--- a/test/bin/modules/test-mod-error-estimation
+++ b/test/bin/modules/test-mod-error-estimation
@@ -49,7 +49,7 @@ echo -n > error_estimation_debug.bob
 
 # create keys
 KEYS_TO_PROCESS="1000"
-${TEST_BASE}/bin/qkd-key-gen --silent --size 512 --keys ${KEYS_TO_PROCESS} --rate 0.03 cat_keys
+${TEST_BASE}/bin/qkd-key-gen --silent --size 512 --keys ${KEYS_TO_PROCESS} --rate 0.03 --random-url=linear-congruential:42 cat_keys
 
 # fix pipeline config
 cat ${TEST_BASE}/test/test-data/pipeline.conf | grep -v "^cat.alice.url_pipe_out" | grep -v "^cat.bob.url_pipe_out" > error-estimation.config
@@ -84,11 +84,11 @@ grep "^key #" error_estimation_debug.alice > error_estimation_debug.alice.out
 grep "^key #" error_estimation_debug.bob > error_estimation_debug.bob.out
 
 if [ ! -s error_estimation_keys.alice ]; then
-    echo "alice has not pushed keys"
+    echo "alice has not pushed any keys"
     exit 1
 fi
 if [ ! -s error_estimation_keys.bob ]; then
-    echo "bob has not pushed keys"
+    echo "bob has not pushed any keys"
     exit 1
 fi
 diff -q error_estimation_debug.alice.out error_estimation_debug.bob.out
@@ -97,7 +97,17 @@ if [ "$?" != "0" ]; then
     exit 1
 fi
 
-echo "qkd-error-estimation work"
+if [[ $(md5sum cat_keys.alice) != 21272a95192ec196cfb00b7c9877f0d5* ]]; then
+    echo "Alice is using unexpected keys (cat_keys.alice) - failed"
+    exit 1
+fi
+
+if [[ $(md5sum cat_keys.bob) != e5db4f8fa5f201b06fd64635627492ac* ]]; then
+    echo "Bob is using unexpected keys (cat_keys.bob) - failed"
+    exit 1
+fi
+
+echo "qkd-error-estimation works as expected"
 
 # state that test ok
 echo "=== TEST SUCCESS ==="
